name: mobiml-viz
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - bokeh<3.0
  - scikit-learn
  - ipykernel
  - hvplot
  - tqdm
  - geopandas
  - geoviews
  - matplotlib
  - black
  - geopy
  - h3-py
  - pyarrow
  - pymeos
  - pyproj
  - movingpandas
  - pytorch
  - opacus
  - folium
  - mapclassify
  - jupyter_bokeh
  - datashader=0.14.4
  - dask
 
