name: mobiml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh<3.0
  - numpy=1.23.4
  - geopandas-base
  - matplotlib-base
  - fiona
  - geopy
  - rtree
  - pytest
  - pytest-cov
  - movingpandas
  - geoviews
  - hvplot
  - jupyter_bokeh
  - pip:
    - flwr