aoi: 
  min_lon: 11.8045
  min_lat: 57.6476
  max_lon: 11.9123
  max_lat: 57.6978
base_model:
  vessel_types: ['Cargo', 'Passenger', 'Tanker']
  traj_features: ['speed_max', 'speed_median', 'x_start', 'y_start', 'x_end', 'y_end', 'length']  # ['SOG_max', 'SOG_median', 'LON_start', 'LAT_start', 'LON_end', 'LAT_end', 'length']  'H3_seq'
  n_features: 7  # 1804  # depends on the number of H3 cells in H3_seq
  test_size: 0.33
extract:
  antennas: ['Point (11.96524 57.70730)', 'Point (11.63979 57.71941)', 'Point (11.78460 57.57255)']
  antenna_radius_meters: 25000 
  vessels: 'Towing'
  vessels_radius_meters: 25000
  bbox: [57.273, 11.196, 57.998, 12.223]
traj_collection:
  min_length: 200 
traj_feature_engineering:
  h3_resolution: 8
datapath: '/mnt/fsdss/AIS_DK'
datasets: ["2017/dk_csv_jul2017.zip", "2017/dk_csv_aug2017.zip", "2017/dk_csv_sep2017.zip", "2017/dk_csv_oct2017.zip", "2017/dk_csv_nov2017.zip", "2017/dk_csv_dec2017.zip", "2018/aisdk-2018-01.zip", "2018/aisdk-2018-02.zip", "2018/aisdk-2018-03.zip", "2018/aisdk-2018-04.zip", "2018/aisdk-2018-05.zip", "2018/aisdk-2018-06.zip",]
outPathAntenna: 'tmp/antenna_data'
datasetsTraining: ["aisdk-2018-02.csv.gz", "aisdk-2018-02.csv.gz"]
datasetsEvaluation: [_aisdk-2018-02.csv.gz]
