name: Tests

on:
  push:
    branches: [ main, uv_structure, 0.** ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v3.0.1

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
            version: 0.5.27
      - name: Run the automated tests
        run: uv run pytest -v -r s --color=yes --cov=mobiml --cov-append --cov-report term-missing --cov-report xml
      - uses: codecov/codecov-action@v5
